### PR TITLE
Moppy with direct Midi in support

### PR DESCRIPTION
**Pull request by MagnusM1709**
Hello,

this is a working Version of Moppy with direct Midi in Support, also adds the ability of Midi out, which sends all the ignored Midi messages out.

It listens to all Midi Channels and to Note on/off messages. 
Also Stereo support (2 Drives play same notes) is added.

if you find bugs typos or something else please write an Comment

### CODE REVIEW

**Comment by SammyIAm** [comment]
Hey there, first off, this looks pretty cool!  I'm sure some other people will be interested in this.  Some comments (in two categories):

### Must Change 
**(At least before this would get pulled into the main repo)**

- The pull request shouldn't modify `MoppyConfig`, `MoppyCore`, or `FloppyDrives`.  I.e. the default should still be normal floppy drives.
- Similarly, the README file should probably stay the same, but information about how to use the code with MIDI support should be added to the wiki (which, I think, can also be edited and pull-requested).
- `MoppyMIDI.*` should go in the existing `MoppyNetworks` directory instead of their own so that `MoppyNetwork.h` isn't duplicated, and everything's kept together.

### Suggestions 
**(I'm not currently able to test the code in the real-world, so as long as it works for you these are just ideas)**

- In `MoppyMidi::readMessages()`, you're checking to make sure the messages have the expected start-bit (>127 or <128) which is good, but there're two potential issues:
  - You probably shouldn't call `readMessages()` again in the block-- as soon as you call `return` the `loop()` function will just call `readMessages` again anyway, and there's a risk of getting stuck endlessly recursing.
  - Not all MIDI events have exactly 3 bytes; many have just 1 or 2.  Rather than always reading all three bytes and then immediately returning if byte 2 or 3 wasn't what you expected, you should only read additional bytes if the first byte requires it.  Basically, read your first byte, make sure it's > 127, and then once you know what it is *then* read the next bytes.  With your current code as-is, a MIDI "Start" event (1 byte long) would result in the next event being skipped over (e.g. the first note of the song might be missing).
- Rather than hard-coding `0x09` in `readMessages`, referencing `NETBYTE_DEV_NOTEON` will make it easier to read what the code is doing, and make sure that if the protocol changes your code will keep working.

**Comment by MagnusM1709** [comment]
Thank you for your good Feedback.

I think I will do some of the Changes on the Weekend.

But i have a Question:
I've never heard of Midi Messages with less then 3 Bytes, especially not with note On/Off, because they deliver in the third Byte the Velocity (Loudness), even as Note Off. But i think i will add a #define for this corner case


The changes in the Moppy Core are necessary, because i need to add the MidiNetwork-Files

**Comment by MagnusM1709** [comment]
> You probably shouldn't call readMessages() again in the block-- as soon as you call return the loop() function will just call readMessages again anyway, and there's a risk of getting stuck endlessly recursing.

I've changed that


> Not all MIDI events have exactly 3 bytes; many have just 1 or 2. Rather than always reading all three bytes and then immediately returning if byte 2 or 3 wasn't what you expected, you should only read additional bytes if the first byte requires it. Basically, read your first byte, make sure it's > 127, and then once you know what it is then read the next bytes. With your current code as-is, a MIDI "Start" event (1 byte long) would result in the next event being skipped over (e.g. the first note of the song might be missing).

Also that

> Rather than hard-coding 0x09 in readMessages, referencing NETBYTE_DEV_NOTEON will make it easier to read what the code is doing, and make sure that if the protocol changes your code will keep working.

And that



If you (or someone else) finds some Issues please Comment, so I can change it

**Comment by SammyIAm** [comment]
Sorry, been busy with stuff lately and haven't checked in on here in a while.

To answer your question, the most common [messages ](https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message) are voice messages which mostly do all have 3 bytes, but a lot of system messages have just 1 or 2.  For the most part these aren't really being interpreted by the Moppy code at this point, but I have seen some people using the `Start` and `Stop` messages to trigger things.

Hopefully I'll have time to take a look at this and pull the code soon, if you don't hear anything for a while, just comment again and bug me ;)

**Comment by vivvvi** [comment]
> Sorry, been busy with stuff lately and haven't checked in on here in a while.
> 
> To answer your question, the most common [messages ](https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message) are voice messages which mostly do all have 3 bytes, but a lot of system messages have just 1 or 2. For the most part these aren't really being interpreted by the Moppy code at this point, but I have seen some people using the `Start` and `Stop` messages to trigger things.
> 
> Hopefully I'll have time to take a look at this and pull the code soon, if you don't hear anything for a while, just comment again and bug me ;)

bounce!

**Comment by SammyIAm** [comment]
Thanks for the bounce, I'd sorta forgot about this!  I'll take a look the next time I'm working on Moppy.

I've been doing some work in the experimental branch, so I'll have to decide if maybe I want to pull some of those changes at the same time.

**Comment by vivvvi** [comment]
no probs sammy, you asked for it :)
Its an attractive proposition to run this as a stand alone device. 

I've just aquired x5 blue pills for $10 (AUD) and already turned them into 2 things.
Sounds like its time to order more!

Is the code  here currently in a working state to flash my bluepill?

**Comment by SammyIAm** [comment]
Merged; sorry it took so long.

@vivvvi To use MoppyMidi, you'll need to uncomment the appropriate lines in `MoppyCore.cpp` and comment out the MoppySerial lines.  Hopefully in a future change I can make that switch easier.

**Comment by Chong-McBong** [comment]
hi sammy, i'm struggling to get this working. is this a typo on line 39? 

it currently says src/MoppyNetworksMidi/MoppyMidi.h

it compiles if i change it to src/MoppyNetworks/MoppyMidi.h, 

but i just get an odd pulsing from the arduinos, and no start up sound. i will keep testing and let you know if i make any progress, 
cheers

**Comment by SammyIAm** [comment]
I've not been able to test the MIDI library myself, so @MagnusM1709 might have a better idea than I do.

That *does* appear to be a typo though, so I think you've made the correct change there.

The lack of startup sound seems to suggest that it's failing even before it gets to the `network.begin()` call in MoppyCore.cpp, since that should happen as part of `instrument.setup()`.  Are you using the `FloppyDrives` instrument, or something else?

You might also try connecting the serial monitor to see if there's any crash or debug information being dumped to the serial connection.

Does it work when you use `MoppySerial`?

**Comment by Chong-McBong** [comment]
cheers :) i will try the serial monitor, i assume thats on the arduino's tx pin, and 5 pin midi connects to the rx pin (or should i be using usb midi?). 

i am using it to run floppies for now, it could be an error at my end, will try again today and see if i can get it working (currently at 34 floppies and 10 HDDs connected, but this is just running a bank of 8 drives for now)

**Pull request merged**
